[package]
name = "datafusion_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = "46.0.0"
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
datafusion-common = "46.0.0"
datafusion-expr = "46.0.0"
datafusion-doc = "46.0.0"
datafusion-macros = "46.0.0"